name: Test macOS Maven Installation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./install-maven-mac.sh

      - name: Run Installation Script
        run: ./install-maven-mac.sh

      - name: Verify Installation
        run: |
          source ~/.zshrc
          mvn --version